### ISSUE TITLE
Errore di firma con Metadata Formato Avviso 29 versione 2

### ISSUE THREAD

**Issue by Alec1bert** [italia/spid-metadata-signer#10]
Salve,
se provo a firmare un metadata contenente i TAG previsti dall'Avviso 29 versione 2, ricevo il seguente errore.

[Fatal Error] :82:16: The prefix "spid" for element "spid:IPACode" is not bound.
ERROR XMLSecTool - XML document was not well formed
org.xml.sax.SAXParseException: The prefix "spid" for element "spid:IPACode" is not bound.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) ~[na:1.8.0_111]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:1.8.0_111]
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.8.0_111]
        at net.shibboleth.tool.xmlsectool.XMLSecTool.parseXML(XMLSecTool.java:187) [xmlsectool-2.0.0.jar:na]
        at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:141) [xmlsectool-2.0.0.jar:na]

Nel metadata il TAG è valorizzato come segue:

        <md:ContactPerson contactType="other">
                <md:Extensions>
                        <spid:IPACode>cIPA_aggregatore</spid:IPACode>
                        <spid:FiscalCode>Fiscal_number</spid:FiscalCode>
                        <spid:Public/>
                </md:Extensions>
                        <md:EmailAddress>indirizzo email</md:EmailAddress>
                        <md:TelephoneNumber>numero di telefono</md:TelephoneNumber>
        </md:ContactPerson>

L'attuale versione di xmlsectool-2.0.0 non è aggiornata o sto sbagliando qualcosa?

Grazie
Saluti

**Comment by Alec1bert** [comment]
Risolto.
